import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "tic,tac,toe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className="bg-gray-100">
        
        <main className="  flex items-center justify-center min-h-screen">
          {children}
        </main>
        
        <footer className="bg-black flex bottom-0  text-teal-400 font-mono justify-center text-center">Made by Muhammad Arham </footer>
      </body>
    </html>
  );
}
